// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: monitoring.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Garm
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PingRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PingResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"server_recv_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? ServerRecvTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"server_send_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? ServerSendTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"client_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"geo_data")]
        public GeoData GeoData { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"under_maintenance")]
        public bool UnderMaintenance { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"scheduled_maintenance")]
        public TimeRange ScheduledMaintenance { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"acid_available")]
        public bool AcidAvailable { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardCountRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardCountResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"update_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? UpdateTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<BoardStat> Datas { get; } = new global::System.Collections.Generic.List<BoardStat>();

        [global::ProtoBuf.ProtoContract()]
        public partial class BoardStat : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"device_type")]
            [global::System.ComponentModel.DefaultValue("")]
            public string DeviceType { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"client_version")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ClientVersion { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"count")]
            public uint Count { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetErrorCountRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetErrorCountResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"update_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? UpdateTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<ErrorStat> Datas { get; } = new global::System.Collections.Generic.List<ErrorStat>();

        [global::ProtoBuf.ProtoMember(3, Name = @"abort_count")]
        public uint AbortCount { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ErrorStat : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"category")]
            public uint Category { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"code")]
            public uint Code { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"error_count")]
            public long ErrorCount { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionCountRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSessionCountResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"update_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? UpdateTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<SessionStat> Datas { get; } = new global::System.Collections.Generic.List<SessionStat>();

        [global::ProtoBuf.ProtoContract()]
        public partial class SessionStat : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"record_time")]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? RecordTime { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"active_count")]
            public long ActiveCount { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"open_count")]
            public long OpenCount { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"close_count")]
            public long CloseCount { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
