// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: types.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Garm
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ExternalID : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"amid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Amid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"mbid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Mbid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ACIDLookup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device")]
        public ACIDDeviceType Device { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"access_code")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccessCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"chip_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChipId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"identity_type")]
        public ACIDIdentityType IdentityType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"qr_seed")]
        [global::System.ComponentModel.DefaultValue("")]
        public string QrSeed { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GeoData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"country")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Country { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Region { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"city")]
        [global::System.ComponentModel.DefaultValue("")]
        public string City { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"latlng")]
        public global::google.type.LatLng Latlng { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TimeRange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? EndTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DateRange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_date")]
        public global::google.type.Date StartDate { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end_date")]
        public global::google.type.Date EndDate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReleaseCondition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? EndTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"require_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequireVersion { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"items")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, long> Items { get; } = new global::System.Collections.Generic.Dictionary<string, long>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CustomData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"items")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Items { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Avatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"items")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Items { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ArcadeSessionData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"credit")]
        public uint Credit { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"service_sw")]
        public uint ServiceSw { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"custom_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CustomData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"free_play")]
        public bool FreePlay { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"trial_play")]
        public bool TrialPlay { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrailData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"meta")]
        public TrailMetaData Meta { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrailMetaData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? EventTime { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"client_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"account_type")]
        public AccountType AccountType { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"account_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"resource_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourceType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"resource_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"action_type")]
        public TrailActionType ActionType { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"action")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Action { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"trace_id")]
        public byte[] TraceId { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13, Name = @"user_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccessLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"namespace")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Namespace { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"event_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? EventTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"client_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"account_type")]
        public AccountType AccountType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"account_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Path { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"status")]
        public global::google.rpc.Status Status { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"latency")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? Latency { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"trace_id")]
        public byte[] TraceId { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13, Name = @"user_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DataChangeLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"namespace")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Namespace { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"event_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? EventTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"client_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"account_type")]
        public AccountType AccountType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"account_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"resource_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourceType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"resource_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResourceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"action_type")]
        public TrailActionType ActionType { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"action")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Action { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"session_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SessionId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"trace_id")]
        public byte[] TraceId { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"user_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public enum NetworkType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_TYPE_INVALID")]
        NetworkTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_TYPE_ALLNET")]
        NetworkTypeAllnet = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NETWORK_TYPE_NBLINE")]
        NetworkTypeNbline = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AllnetLineType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALLNET_LINE_TYPE_INVALID")]
        AllnetLineTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ALLNET_LINE_TYPE_MOBILE")]
        AllnetLineTypeMobile = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ALLNET_LINE_TYPE_ISDN")]
        AllnetLineTypeIsdn = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ALLNET_LINE_TYPE_BFLETS")]
        AllnetLineTypeBflets = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ALLNET_LINE_TYPE_ADSL")]
        AllnetLineTypeAdsl = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CardStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_INVALID")]
        CardStatusInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_OK")]
        CardStatusOk = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_UNUSED")]
        CardStatusUnused = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_LOCKED")]
        CardStatusLocked = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_DISABLED")]
        CardStatusDisabled = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_USED")]
        CardStatusUsed = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"CARD_STATUS_REISSUE")]
        CardStatusReissue = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ACIDDeviceType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_DEVICE_TYPE_INVALID")]
        AcidDeviceTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_DEVICE_TYPE_CARD")]
        AcidDeviceTypeCard = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_DEVICE_TYPE_MOBILE")]
        AcidDeviceTypeMobile = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_DEVICE_TYPE_QR")]
        AcidDeviceTypeQr = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ACIDIdentityType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_IDENTITY_TYPE_INVALID")]
        AcidIdentityTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_IDENTITY_TYPE_BNG")]
        AcidIdentityTypeBng = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_IDENTITY_TYPE_SEGA")]
        AcidIdentityTypeSega = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_IDENTITY_TYPE_MOBILE")]
        AcidIdentityTypeMobile = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_IDENTITY_TYPE_AICC")]
        AcidIdentityTypeAicc = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ACID_IDENTITY_TYPE_QR")]
        AcidIdentityTypeQr = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum UserType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"USER_TYPE_INVALID")]
        UserTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"USER_TYPE_GUEST")]
        UserTypeGuest = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"USER_TYPE_ACID")]
        UserTypeAcid = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"USER_TYPE_FAKE")]
        UserTypeFake = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DisplayNameChangeState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"DISPLAY_NAME_CHANGE_STATE_INVALID")]
        DisplayNameChangeStateInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPLAY_NAME_CHANGE_STATE_NONE")]
        DisplayNameChangeStateNone = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPLAY_NAME_CHANGE_STATE_USER")]
        DisplayNameChangeStateUser = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPLAY_NAME_CHANGE_STATE_FORCE")]
        DisplayNameChangeStateForce = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_TYPE_INVALID")]
        AccountTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_TYPE_INTERNAL")]
        AccountTypeInternal = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_TYPE_EMBEDDED")]
        AccountTypeEmbedded = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_TYPE_SERVICE")]
        AccountTypeService = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_TYPE_MAILBASE")]
        AccountTypeMailbase = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum NamespaceState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_INVALID")]
        NamespaceStateInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_INITIALIZE")]
        NamespaceStateInitialize = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_READY")]
        NamespaceStateReady = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_STOP_WAIT")]
        NamespaceStateStopWait = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_STOP")]
        NamespaceStateStop = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_TERMINATE")]
        NamespaceStateTerminate = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"NAMESPACE_STATE_TERMINATED")]
        NamespaceStateTerminated = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LastSessionState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_SESSION_STATE_INVALID")]
        LastSessionStateInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_SESSION_STATE_OK")]
        LastSessionStateOk = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_SESSION_STATE_CANCEL")]
        LastSessionStateCancel = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_SESSION_STATE_TEST_SW")]
        LastSessionStateTestSw = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_SESSION_STATE_ABORT")]
        LastSessionStateAbort = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"LAST_SESSION_STATE_TIMEOUT")]
        LastSessionStateTimeout = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AchivementType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACHIVEMENT_TYPE_INVALID")]
        AchivementTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACHIVEMENT_TYPE_ONE_SHOT")]
        AchivementTypeOneShot = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACHIVEMENT_TYPE_PERCENTAGE")]
        AchivementTypePercentage = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ACHIVEMENT_TYPE_COUNTER")]
        AchivementTypeCounter = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AggregateUnit
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_INVALID")]
        AggregateUnitInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_HOUR")]
        AggregateUnitHour = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_DAY")]
        AggregateUnitDay = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_WEEK")]
        AggregateUnitWeek = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_MONTH")]
        AggregateUnitMonth = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_QUARTER")]
        AggregateUnitQuarter = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_UNIT_YEAR")]
        AggregateUnitYear = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AggregateRegion
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_REGION_INVALID")]
        AggregateRegionInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_REGION_ALL")]
        AggregateRegionAll = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_REGION_COUNTRY")]
        AggregateRegionCountry = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_REGION_AREA")]
        AggregateRegionArea = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"AGGREGATE_REGION_LOCATION")]
        AggregateRegionLocation = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum StorageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_INVALID")]
        StorageTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_LOCAL")]
        StorageTypeLocal = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_S3")]
        StorageTypeS3 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"STORAGE_TYPE_GCS")]
        StorageTypeGcs = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ScriptType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SCRIPT_TYPE_INVALID")]
        ScriptTypeInvalid = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TrailActionType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TRAIL_ACTION_TYPE_INVALID")]
        TrailActionTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAIL_ACTION_TYPE_CREATE")]
        TrailActionTypeCreate = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAIL_ACTION_TYPE_UPDATE")]
        TrailActionTypeUpdate = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TRAIL_ACTION_TYPE_DELETE")]
        TrailActionTypeDelete = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlayLogState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_INVALID")]
        PlayLogStateInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_PROGRESS")]
        PlayLogStateProgress = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_CLOSED")]
        PlayLogStateClosed = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_LEAVE")]
        PlayLogStateLeave = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_TEST_SW")]
        PlayLogStateTestSw = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_NET_ERROR")]
        PlayLogStateNetError = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_LAN_ERROR")]
        PlayLogStateLanError = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_TIMEOUT")]
        PlayLogStateTimeout = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAY_LOG_STATE_ABORT")]
        PlayLogStateAbort = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ActivityType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACTIVITY_TYPE_INVALID")]
        ActivityTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACTIVITY_TYPE_DATA_CHANGE")]
        ActivityTypeDataChange = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReferenceType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"REFERENCE_TYPE_INVALID")]
        ReferenceTypeInvalid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"REFERENCE_TYPE_PLAY")]
        ReferenceTypePlay = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
