<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TaikoLocalServer.Adapters.AdminApi</RootNamespace>
    <AssemblyName>TaikoLocalServer.Adapters.AdminApi</AssemblyName>
    <NoWarn>$(NoWarn);RMG020;RMG012</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Contracts.AdminApi\Contracts.AdminApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Otp.NET" />
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="Throw" />
  </ItemGroup>

</Project>
