// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: systemboard.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Garm
{
    [global::ProtoBuf.ProtoContract()]
    public partial class SystemBoardData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"create_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? CreateTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"update_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? UpdateTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"client_ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientIp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"geo_data")]
        public GeoData GeoData { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"client_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? ClientTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"is_after_boot")]
        public bool IsAfterBoot { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"is_after_auth")]
        public bool IsAfterAuth { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"device_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"network_type")]
        public NetworkType NetworkType { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"client_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(13, Name = @"station_no", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int StationNo { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"parent_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ParentDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"test_mode_setting")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TestModeSetting { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16, Name = @"bookkeeping_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BookkeepingData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(17, Name = @"allnet_opt")]
        public AllnetOption AllnetOpt { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"device_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19, Name = @"os_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OsName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(20, Name = @"os_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OsVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(21, Name = @"mac_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MacAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(22, Name = @"mucha_verified")]
        public bool MuchaVerified { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class AllnetOption : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"allnet_version")]
            [global::System.ComponentModel.DefaultValue("")]
            public string AllnetVersion { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"tenporouter_ip")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TenporouterIp { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"hop_count")]
            public int HopCount { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"traceroute")]
            public global::System.Collections.Generic.List<string> Traceroutes { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(5, Name = @"line_type")]
            public AllnetLineType LineType { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterSystemBoardRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public SystemBoardData Data { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"location_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"location_address")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationAddress { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"location_country")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationCountry { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"location_region")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationRegion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"mucha_auth_token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MuchaAuthToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterSystemBoardResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"data")]
        public SystemBoardData Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchSystemBoardsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"limit")]
        public uint Limit { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId
        {
            get => __pbn__condition_oneof.Is(1) ? ((string)__pbn__condition_oneof.Object) : "";
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(1, value);
        }
        public bool ShouldSerializeLocationId() => __pbn__condition_oneof.Is(1);
        public void ResetLocationId() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__condition_oneof;

        [global::ProtoBuf.ProtoMember(2, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId
        {
            get => __pbn__condition_oneof.Is(2) ? ((string)__pbn__condition_oneof.Object) : "";
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeDeviceId() => __pbn__condition_oneof.Is(2);
        public void ResetDeviceId() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"update_range")]
        public TimeRange UpdateRange
        {
            get => __pbn__condition_oneof.Is(3) ? ((TimeRange)__pbn__condition_oneof.Object) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeUpdateRange() => __pbn__condition_oneof.Is(3);
        public void ResetUpdateRange() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"update_latest")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? UpdateLatest
        {
            get => __pbn__condition_oneof.Is(4) ? ((global::System.TimeSpan?)__pbn__condition_oneof.TimeSpan) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(4, value);
        }
        public bool ShouldSerializeUpdateLatest() => __pbn__condition_oneof.Is(4);
        public void ResetUpdateLatest() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 4);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchSystemBoardsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"boards")]
        public global::System.Collections.Generic.List<Board> Boards { get; } = new global::System.Collections.Generic.List<Board>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Board : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"device_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string DeviceId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"device_type")]
            [global::System.ComponentModel.DefaultValue("")]
            public string DeviceType { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"network_type")]
            public NetworkType NetworkType { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"client_version")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ClientVersion { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"location_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string LocationId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"station_no", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
            public int StationNo { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"parent_device_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ParentDeviceId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(8, Name = @"update_time")]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? UpdateTime { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"mucha_verified")]
            public bool MuchaVerified { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateSystemBoardDataRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"station_no", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int StationNo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"parent_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ParentDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"test_mode_setting")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TestModeSetting { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"bookkeeping_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BookkeepingData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"client_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? ClientTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateSystemBoardDataResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardDataRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardDataResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"station_no", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int StationNo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"test_mode_setting")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TestModeSetting { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"bookkeeping_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BookkeepingData { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ErrorLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_log_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorLogId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"receive_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? ReceiveTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"count")]
        public uint Count { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"error_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? ErrorTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"category")]
        public uint Category { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"code")]
        public uint Code { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"sequence")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sequence { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"custom_data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CustomData { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"attache_files")]
        public global::System.Collections.Generic.List<string> AttacheFiles { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(12, Name = @"exit_code", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int ExitCode { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"stack_trace")]
        public global::System.Collections.Generic.List<string> StackTraces { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(14, Name = @"core_dump")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CoreDump { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"sender_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16, Name = @"sender_location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderLocationId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterSystemBoardErrorLogRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_logs")]
        public global::System.Collections.Generic.List<ErrorLog> ErrorLogs { get; } = new global::System.Collections.Generic.List<ErrorLog>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterSystemBoardErrorLogResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"upload_url")]
        public global::System.Collections.Generic.List<UploadURL> UploadUrls { get; } = new global::System.Collections.Generic.List<UploadURL>();

        [global::ProtoBuf.ProtoMember(2, Name = @"warnings")]
        public global::System.Collections.Generic.List<Warning> Warnings { get; } = new global::System.Collections.Generic.List<Warning>();

        [global::ProtoBuf.ProtoMember(3, Name = @"too_many")]
        public bool TooMany { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class UploadURL : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"error_log_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ErrorLogId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"attache_files")]
            public global::System.Collections.Generic.List<string> AttacheFiles { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(3, Name = @"core_dump")]
            [global::System.ComponentModel.DefaultValue("")]
            public string CoreDump { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Warning : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"error_log_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ErrorLogId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"messages")]
            public global::System.Collections.Generic.List<string> Messages { get; } = new global::System.Collections.Generic.List<string>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardErrorLogRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"error_log_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrorLogId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardErrorLogResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_log")]
        public ErrorLog ErrorLog { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListSystemBoardErrorLogsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sender_device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SenderDeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"limit")]
        public uint Limit { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"range")]
        public TimeRange Range
        {
            get => __pbn__condition_oneof.Is(2) ? ((TimeRange)__pbn__condition_oneof.Object) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeRange() => __pbn__condition_oneof.Is(2);
        public void ResetRange() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 2);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__condition_oneof;

        [global::ProtoBuf.ProtoMember(3, Name = @"latest")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? Latest
        {
            get => __pbn__condition_oneof.Is(3) ? ((global::System.TimeSpan?)__pbn__condition_oneof.TimeSpan) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeLatest() => __pbn__condition_oneof.Is(3);
        public void ResetLatest() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListSystemBoardErrorLogsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_logs")]
        public global::System.Collections.Generic.List<ErrorLog> ErrorLogs { get; } = new global::System.Collections.Generic.List<ErrorLog>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListSystemBoardAbortLogsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(15, Name = @"limit")]
        public uint Limit { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"range")]
        public TimeRange Range
        {
            get => __pbn__condition_oneof.Is(1) ? ((TimeRange)__pbn__condition_oneof.Object) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(1, value);
        }
        public bool ShouldSerializeRange() => __pbn__condition_oneof.Is(1);
        public void ResetRange() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__condition_oneof;

        [global::ProtoBuf.ProtoMember(2, Name = @"latest")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? Latest
        {
            get => __pbn__condition_oneof.Is(2) ? ((global::System.TimeSpan?)__pbn__condition_oneof.TimeSpan) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeLatest() => __pbn__condition_oneof.Is(2);
        public void ResetLatest() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 2);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListSystemBoardAbortLogsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error_logs")]
        public global::System.Collections.Generic.List<ErrorLog> ErrorLogs { get; } = new global::System.Collections.Generic.List<ErrorLog>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchRequestLogsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchRequestLogsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchSystemBoardTrailsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"device_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15, Name = @"limit")]
        public uint Limit { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"range")]
        public TimeRange Range
        {
            get => __pbn__condition_oneof.Is(2) ? ((TimeRange)__pbn__condition_oneof.Object) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeRange() => __pbn__condition_oneof.Is(2);
        public void ResetRange() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 2);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__condition_oneof;

        [global::ProtoBuf.ProtoMember(3, Name = @"latest")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.TimeSpan? Latest
        {
            get => __pbn__condition_oneof.Is(3) ? ((global::System.TimeSpan?)__pbn__condition_oneof.TimeSpan) : default;
            set => __pbn__condition_oneof = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeLatest() => __pbn__condition_oneof.Is(3);
        public void ResetLatest() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__condition_oneof, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchSystemBoardTrailsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trails")]
        public global::System.Collections.Generic.List<TrailData> Trails { get; } = new global::System.Collections.Generic.List<TrailData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardTrailRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetSystemBoardTrailResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"meta")]
        public TrailMetaData Meta { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public SystemBoardData Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Billing : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"billing_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BillingType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"net_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NetId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"play_time")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? PlayTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"play_type")]
        public uint PlayType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"amount")]
        public uint Amount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterSystemBoardBillingRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"billing")]
        public global::System.Collections.Generic.List<Billing> Billings { get; } = new global::System.Collections.Generic.List<Billing>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterSystemBoardBillingResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"warnings")]
        public global::System.Collections.Generic.List<Warning> Warnings { get; } = new global::System.Collections.Generic.List<Warning>();

        [global::ProtoBuf.ProtoMember(2, Name = @"too_many")]
        public bool TooMany { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Warning : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
            public global::System.Collections.Generic.List<string> Messages { get; } = new global::System.Collections.Generic.List<string>();

            [global::ProtoBuf.ProtoMember(2, Name = @"billing_type")]
            [global::System.ComponentModel.DefaultValue("")]
            public string BillingType { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"net_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string NetId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"location_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string LocationId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"play_time")]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? PlayTime { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"play_type")]
            public uint PlayType { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"amount")]
            public uint Amount { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchSystemBoardBillingRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"location_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocationId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"billing_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BillingType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"summary_date")]
        public global::google.type.Date SummaryDate { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"net_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NetId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchSystemBoardBillingResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"total")]
        public uint Total { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"billing")]
        public global::System.Collections.Generic.List<RegisteredBilling> Billings { get; } = new global::System.Collections.Generic.List<RegisteredBilling>();

        [global::ProtoBuf.ProtoContract()]
        public partial class RegisteredBilling : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(4, Name = @"net_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string NetId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"sender_place_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string SenderPlaceId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"play_time")]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? PlayTime { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"received_time")]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? ReceivedTime { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"received_date")]
            public global::google.type.Date ReceivedDate { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"hc2_received_time")]
            [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
            public global::System.DateTime? Hc2ReceivedTime { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"summary_date")]
            public global::google.type.Date SummaryDate { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"play_type")]
            public uint PlayType { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"amount")]
            public uint Amount { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
