<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TaikoLocalServer.Adapters.GameProtocol.Shared</RootNamespace>
    <AssemblyName>TaikoLocalServer.Adapters.GameProtocol.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="protobuf-net.AspNetCore" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="Swan.Core" />
  </ItemGroup>

</Project>
