<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>TaikoLocalServer.Infrastructure</RootNamespace>
        <AssemblyName>TaikoLocalServer.Infrastructure</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
        <ProjectReference Include="..\Contracts.AdminApi\Contracts.AdminApi.csproj" />
        <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="GameDataCatalog\Ac15\Schemas\ac15-challenge-compe-catalog.schema.json" />
        <EmbeddedResource Include="GameDataCatalog\Ac15\Schemas\ac15-challenge-compe-catalog.schema.json">
            <LogicalName>TaikoLocalServer.Infrastructure.GameDataCatalog.Ac15.Schemas.ac15-challenge-compe-catalog.schema.json</LogicalName>
        </EmbeddedResource>
        <Content Include="GameDataCatalog\Ac15\Schemas\ac15-challenge-compe-catalog.schema.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <TargetPath>schemas\ac15-challenge-compe-catalog.schema.json</TargetPath>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" />
        <PackageReference Include="EntityFrameworkCore.Exceptions.Sqlite" />
        <PackageReference Include="JsonSchema.Net" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SharpZipLib" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
        <PackageReference Include="Throw" />
        <PackageReference Include="Yoh.Text.Json.NamingPolicies" />
    </ItemGroup>

</Project>
