namespace TaikoLocalServer.Application.Ac15;

public sealed record Ac15UserSettingsAccess<TSave>(
    Func<TSave, string> GetTitle,
    Action<TSave, string> SetTitle,
    Func<TSave, uint> GetTitlePlateId,
    Action<TSave, uint> SetTitlePlateId,
    Func<TSave, uint> GetToneId,
    Action<TSave, uint> SetToneId,
    Func<TSave, uint> GetCostume1,
    Action<TSave, uint> SetCostume1,
    Func<TSave, uint> GetCostume2,
    Action<TSave, uint> SetCostume2,
    Func<TSave, uint> GetCostume3,
    Action<TSave, uint> SetCostume3,
    Func<TSave, uint> GetCostume4,
    Action<TSave, uint> SetCostume4,
    Func<TSave, uint> GetCostume5,
    Action<TSave, uint> SetCostume5,
    Func<TSave, byte[]> GetCostumeFlg1,
    Action<TSave, byte[]> SetCostumeFlg1,
    Func<TSave, byte[]> GetCostumeFlg2,
    Action<TSave, byte[]> SetCostumeFlg2,
    Func<TSave, byte[]> GetCostumeFlg3,
    Action<TSave, byte[]> SetCostumeFlg3,
    Func<TSave, byte[]> GetCostumeFlg4,
    Action<TSave, byte[]> SetCostumeFlg4,
    Func<TSave, byte[]> GetCostumeFlg5,
    Action<TSave, byte[]> SetCostumeFlg5,
    Func<TSave, byte[]> GetTitleFlg,
    Action<TSave, byte[]> SetTitleFlg,
    Func<TSave, byte[]> GetToneFlg,
    Action<TSave, byte[]> SetToneFlg,
    Func<TSave, uint> GetColorBody,
    Action<TSave, uint> SetColorBody,
    Func<TSave, uint> GetColorFace,
    Action<TSave, uint> SetColorFace,
    Func<TSave, uint> GetColorLimb,
    Action<TSave, uint> SetColorLimb,
    Func<TSave, uint> GetDispDanType,
    Action<TSave, uint> SetDispDanType,
    Func<TSave, uint> GetDispTaikojukuDan,
    Action<TSave, uint> SetDispTaikojukuDan,
    Func<TSave, bool> GetIsTojiru,
    Action<TSave, bool> SetIsTojiru,
    Func<TSave, bool> GetIsAutoCostumeOn,
    Action<TSave, bool> SetIsAutoCostumeOn,
    Func<TSave, uint> GetDispLevelChassis,
    Action<TSave, uint> SetDispLevelChassis,
    Func<TSave, uint> GetDispLevelSelf,
    Action<TSave, uint> SetDispLevelSelf,
    Func<TSave, DateTime> GetLastPlayDatetime,
    int CostumeFlagBytes,
    int TitleFlagBytes,
    int ToneFlagBytes);

public static class Ac15UserSettingsAccess
{
    public static Ac15UserSettingsAccess<UserSaveDataBlue> Blue { get; } = CreateBlue();
    public static Ac15UserSettingsAccess<UserSaveDataGreen> Green { get; } = CreateGreen();
    public static Ac15UserSettingsAccess<UserSaveDataYellow> Yellow { get; } = CreateYellow();
    public static Ac15UserSettingsAccess<UserSaveDataRed> Red { get; } = CreateRed();

    private static Ac15UserSettingsAccess<UserSaveDataBlue> CreateBlue()
        => new(
            save => save.Title, (save, value) => save.Title = value,
            save => save.TitleplateId, (save, value) => save.TitleplateId = value,
            save => save.DefaultToneSetting, (save, value) => save.DefaultToneSetting = value,
            save => save.Costume1, (save, value) => save.Costume1 = value,
            save => save.Costume2, (save, value) => save.Costume2 = value,
            save => save.Costume3, (save, value) => save.Costume3 = value,
            save => save.Costume4, (save, value) => save.Costume4 = value,
            save => save.Costume5, (save, value) => save.Costume5 = value,
            save => save.CostumeFlg1, (save, value) => save.CostumeFlg1 = value,
            save => save.CostumeFlg2, (save, value) => save.CostumeFlg2 = value,
            save => save.CostumeFlg3, (save, value) => save.CostumeFlg3 = value,
            save => save.CostumeFlg4, (save, value) => save.CostumeFlg4 = value,
            save => save.CostumeFlg5, (save, value) => save.CostumeFlg5 = value,
            save => save.TitleFlg, (save, value) => save.TitleFlg = value,
            save => save.ToneFlg, (save, value) => save.ToneFlg = value,
            save => save.ColorBody, (save, value) => save.ColorBody = value,
            save => save.ColorFace, (save, value) => save.ColorFace = value,
            save => save.ColorLimb, (save, value) => save.ColorLimb = value,
            save => save.DispDanType, (save, value) => save.DispDanType = value,
            save => save.DispTaikojukuDan, (save, value) => save.DispTaikojukuDan = value,
            save => save.IsTojiru, (save, value) => save.IsTojiru = value,
            save => save.IsAutoCostumeOn, (save, value) => save.IsAutoCostumeOn = value,
            save => save.DispLevelChassis, (save, value) => save.DispLevelChassis = value,
            save => save.DispLevelSelf, (save, value) => save.DispLevelSelf = value,
            save => save.LastPlayDatetime,
            BlueProtocolBytes.CostumeFlagBytes,
            BlueProtocolBytes.TitleFlagBytes,
            BlueProtocolBytes.ToneFlagBytes);

    private static Ac15UserSettingsAccess<UserSaveDataGreen> CreateGreen()
        => new(
            save => save.Title, (save, value) => save.Title = value,
            save => save.TitleplateId, (save, value) => save.TitleplateId = value,
            save => save.DefaultToneSetting, (save, value) => save.DefaultToneSetting = value,
            save => save.Costume1, (save, value) => save.Costume1 = value,
            save => save.Costume2, (save, value) => save.Costume2 = value,
            save => save.Costume3, (save, value) => save.Costume3 = value,
            save => save.Costume4, (save, value) => save.Costume4 = value,
            save => save.Costume5, (save, value) => save.Costume5 = value,
            save => save.CostumeFlg1, (save, value) => save.CostumeFlg1 = value,
            save => save.CostumeFlg2, (save, value) => save.CostumeFlg2 = value,
            save => save.CostumeFlg3, (save, value) => save.CostumeFlg3 = value,
            save => save.CostumeFlg4, (save, value) => save.CostumeFlg4 = value,
            save => save.CostumeFlg5, (save, value) => save.CostumeFlg5 = value,
            save => save.TitleFlg, (save, value) => save.TitleFlg = value,
            save => save.ToneFlg, (save, value) => save.ToneFlg = value,
            save => save.ColorBody, (save, value) => save.ColorBody = value,
            save => save.ColorFace, (save, value) => save.ColorFace = value,
            save => save.ColorLimb, (save, value) => save.ColorLimb = value,
            save => save.DispDanType, (save, value) => save.DispDanType = value,
            save => save.DispTaikojukuDan, (save, value) => save.DispTaikojukuDan = value,
            save => save.IsTojiru, (save, value) => save.IsTojiru = value,
            save => save.IsAutoCostumeOn, (save, value) => save.IsAutoCostumeOn = value,
            save => save.DispLevelChassis, (save, value) => save.DispLevelChassis = value,
            save => save.DispLevelSelf, (save, value) => save.DispLevelSelf = value,
            save => save.LastPlayDatetime,
            GreenProtocolBytes.CostumeFlagBytes,
            GreenProtocolBytes.TitleFlagBytes,
            GreenProtocolBytes.ToneFlagBytes);

    private static Ac15UserSettingsAccess<UserSaveDataYellow> CreateYellow()
        => new(
            save => save.Title, (save, value) => save.Title = value,
            save => save.TitleplateId, (save, value) => save.TitleplateId = value,
            save => save.DefaultToneSetting, (save, value) => save.DefaultToneSetting = value,
            save => save.Costume1, (save, value) => save.Costume1 = value,
            save => save.Costume2, (save, value) => save.Costume2 = value,
            save => save.Costume3, (save, value) => save.Costume3 = value,
            save => save.Costume4, (save, value) => save.Costume4 = value,
            save => save.Costume5, (save, value) => save.Costume5 = value,
            save => save.CostumeFlg1, (save, value) => save.CostumeFlg1 = value,
            save => save.CostumeFlg2, (save, value) => save.CostumeFlg2 = value,
            save => save.CostumeFlg3, (save, value) => save.CostumeFlg3 = value,
            save => save.CostumeFlg4, (save, value) => save.CostumeFlg4 = value,
            save => save.CostumeFlg5, (save, value) => save.CostumeFlg5 = value,
            save => save.TitleFlg, (save, value) => save.TitleFlg = value,
            save => save.ToneFlg, (save, value) => save.ToneFlg = value,
            save => save.ColorBody, (save, value) => save.ColorBody = value,
            save => save.ColorFace, (save, value) => save.ColorFace = value,
            save => save.ColorLimb, (save, value) => save.ColorLimb = value,
            save => save.DispDanType, (save, value) => save.DispDanType = value,
            save => save.DispTaikojukuDan, (save, value) => save.DispTaikojukuDan = value,
            save => save.IsTojiru, (save, value) => save.IsTojiru = value,
            save => save.IsAutoCostumeOn, (save, value) => save.IsAutoCostumeOn = value,
            save => save.DispLevelChassis, (save, value) => save.DispLevelChassis = value,
            save => save.DispLevelSelf, (save, value) => save.DispLevelSelf = value,
            save => save.LastPlayDatetime,
            Ac15EraProfiles.Yellow.Limits.CostumeFlagBytes,
            Ac15EraProfiles.Yellow.Limits.TitleFlagBytes,
            Ac15EraProfiles.Yellow.Limits.ToneFlagBytes);

    private static Ac15UserSettingsAccess<UserSaveDataRed> CreateRed()
        => new(
            save => save.Title, (save, value) => save.Title = value,
            save => save.TitleplateId, (save, value) => save.TitleplateId = value,
            save => save.DefaultToneSetting, (save, value) => save.DefaultToneSetting = value,
            save => save.Costume1, (save, value) => save.Costume1 = value,
            save => save.Costume2, (save, value) => save.Costume2 = value,
            save => save.Costume3, (save, value) => save.Costume3 = value,
            save => save.Costume4, (save, value) => save.Costume4 = value,
            save => save.Costume5, (save, value) => save.Costume5 = value,
            save => save.CostumeFlg1, (save, value) => save.CostumeFlg1 = value,
            save => save.CostumeFlg2, (save, value) => save.CostumeFlg2 = value,
            save => save.CostumeFlg3, (save, value) => save.CostumeFlg3 = value,
            save => save.CostumeFlg4, (save, value) => save.CostumeFlg4 = value,
            save => save.CostumeFlg5, (save, value) => save.CostumeFlg5 = value,
            save => save.TitleFlg, (save, value) => save.TitleFlg = value,
            save => save.ToneFlg, (save, value) => save.ToneFlg = value,
            save => save.ColorBody, (save, value) => save.ColorBody = value,
            save => save.ColorFace, (save, value) => save.ColorFace = value,
            save => save.ColorLimb, (save, value) => save.ColorLimb = value,
            save => save.DispDanType, (save, value) => save.DispDanType = value,
            save => save.DispTaikojukuDan, (save, value) => save.DispTaikojukuDan = value,
            save => save.IsTojiru, (save, value) => save.IsTojiru = value,
            save => save.IsAutoCostumeOn, (save, value) => save.IsAutoCostumeOn = value,
            save => save.DispLevelChassis, (save, value) => save.DispLevelChassis = value,
            save => save.DispLevelSelf, (save, value) => save.DispLevelSelf = value,
            save => save.LastPlayDatetime,
            Ac15EraProfiles.Red.Limits.CostumeFlagBytes,
            Ac15EraProfiles.Red.Limits.TitleFlagBytes,
            Ac15EraProfiles.Red.Limits.ToneFlagBytes);
}
